network.host: 0.0.0.0
discovery.type: "single-node"
xpack.security.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/logs

http.cors.enabled: true
http.cors.allow-origin: http://localhost:5601
