FROM nginx
RUN rm -rf /etc/nginx/conf.d/default.conf
RUN rm -rf /etc/nginx/nginx.conf
COPY ./nginx/conf.d/nginx.conf /etc/nginx/conf.d
COPY ./nginx/nginx.conf /etc/nginx
CMD ["nginx", "-g", "daemon off;"]
