package poke.rogue.helper.local

import poke.rogue.helper.data.model.MatchedResult
import poke.rogue.helper.data.model.TypeInfo

object DummyTypeData {
    val allTypes =
        listOf(
            TypeInfo(0, "노말"),
            TypeInfo(1, "불꽃"),
            TypeInfo(2, "물"),
            TypeInfo(3, "전기"),
            TypeInfo(4, "풀"),
            TypeInfo(5, "얼음"),
            TypeInfo(6, "격투"),
            TypeInfo(7, "독"),
            TypeInfo(8, "땅"),
            TypeInfo(9, "비행"),
            TypeInfo(10, "에스퍼"),
            TypeInfo(11, "벌레"),
            TypeInfo(12, "바위"),
            TypeInfo(13, "고스트"),
            TypeInfo(14, "드래곤"),
            TypeInfo(15, "악"),
            TypeInfo(16, "강철"),
            TypeInfo(17, "페어리"),
        )

    val typeMatchedTable =
        arrayOf(
            // 노말
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.INEFFECTIVE,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
            ),
            // 불꽃
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
            ),
            // 물
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
            ),
            // 전기
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.WEAK,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.INEFFECTIVE,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
            ),
            // 풀
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.STRONG,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
            ),
            // 얼음
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
            ),
            // 격투
            arrayOf(
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.WEAK,
                MatchedResult.WEAK,
                MatchedResult.STRONG,
                MatchedResult.INEFFECTIVE,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.STRONG,
                MatchedResult.WEAK,
            ),
            // 독
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.INEFFECTIVE,
                MatchedResult.STRONG,
            ),
            // 땅
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.INEFFECTIVE,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
            ),
            // 비행
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
            ),
            // 에스퍼
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.INEFFECTIVE,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
            ),
            // 벌레
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.WEAK,
                MatchedResult.WEAK,
            ),
            // 바위
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
            ),
            // 고스트
            arrayOf(
                MatchedResult.INEFFECTIVE,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
            ),
            // 드래곤
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.INEFFECTIVE,
            ),
            // 악
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
            ),
            // 강철
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.WEAK,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.STRONG,
            ),
            // 페어리
            arrayOf(
                MatchedResult.NORMAL,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.NORMAL,
                MatchedResult.STRONG,
                MatchedResult.STRONG,
                MatchedResult.WEAK,
                MatchedResult.NORMAL,
            ),
        )
}
