name: Add Labels Action

permissions:
  contents: read
  pull-requests: write

runs:
  using: 'composite'
  steps:
    - name: add FEAT ✨ labels
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ contains(github.event.pull_request.title, 'FEAT') }}
      with:
        labels: |
          AN_FEAT ✨

    - name: add UI 🎨 labels
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ contains(github.event.pull_request.title, 'UI') }}
      with:
        labels: |
          AN_UI 🎨

    - name: add REFACTOR ✍️ label
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ contains(github.event.pull_request.title, 'REFACTOR') }}
      with:
        labels: |
          AN_REFACTOR ✍️

    - name: add FIX 🐛 label
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ contains(github.event.pull_request.title, 'FIX') }}
      with:
        labels: |
          AN_FIX 🐛

    - name: add CI/CD 🤖 label
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ contains(github.event.pull_request.title, 'CI') || contains(github.event.pull_request.title, 'CD') }}
      with:
        labels: |
          AN_CI/CD 🤖

    - name: add CONFIG 🧭 label
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ contains(github.event.pull_request.title, 'CONFIG') }}
      with:
        labels: |
          AN_CONFIG 🧭
