name: Backend Production Server CD All

permissions:
  contents: read

on:
  push:
    branches: [ "be/release-test" ]
    tags:
      - 'v*'

jobs:
  prod_a:
    name: Backend Production Server CD A
    uses: ./.github/workflows/Backend-CD-Prod-A.yml
    secrets: inherit
  prod_b:
    needs: prod_a
    name: Backend Production Server CD B
    uses: ./.github/workflows/Backend-CD-Prod-B.yml
    secrets: inherit
