name: Backend CI

on:
  pull_request:
    branches: [ "be/develop" ]
  push:
    branches: [ "be/develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Local MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'pokerogue'
          mysql user: ${{ secrets.TEST_DB_USERNAME }}
          mysql password: ${{ secrets.TEST_DB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Test MySQL
        run: |
          sudo touch docker-compose.yml
          echo "${{ vars.DOCKER_COMPOSE_TEST_DB }}" | sudo tee docker-compose.yml > /dev/null
          docker-compose -f docker-compose.yml up -d
        working-directory: ./backend/pokerogue

      - name: Wait for Test MySQL to be ready
        run: |
          for i in {1..30}; do
          if docker-compose exec -T pokerogue-db mysqladmin ping --host 127.0.0.1 --user ${{ secrets.TEST_DB_USERNAME }} --password=${{ secrets.TEST_DB_PASSWORD }} --silent; then
          echo "MySQL is up and running!"
          break
          else
          echo "Waiting for MySQL to be ready..."
          docker logs pokerogue-db
          sleep 5
          fi
          done
        working-directory: ./backend/pokerogue

      - name: Run Test
        run: SPRING_PROFILES_ACTIVE=local-mysql ./gradlew clean test
        working-directory: ./backend/pokerogue
