name: Backend CI

on:
  pull_request:
    branches: [ "be/develop" ]
  push:
    branches: [ "be/infra/#182-manage-yml-files" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ci
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Remove Containers
        run: |
          docker ps -aq | xargs -r docker rm -vf

      - name: Set up Local MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'pokerogue'
          mysql user: ${{ secrets.TEST_DB_USERNAME }}
          mysql password: ${{ secrets.TEST_DB_PASSWORD }}

      - name: Upload Docker Compose File
        uses: actions/upload-artifact@v4
        with:
          name: pokerogue-helper-ci-yml
          path: ./backend/pokerogue/src/main/resources/docker-compose-ci.yml

      - name: Download Docker Compose File
        uses: actions/download-artifact@v4
        with:
          name: pokerogue-helper-ci-yml
          path: .

      - name: Set up Test MySQL
        run: docker-compose -f docker-compose-ci.yml up -d

      - name: Wait for Test MySQL to be ready
        run: |
          for i in {1..30}; do
          if docker-compose exec -T pokerogue-db mysqladmin ping --host 127.0.0.1 --user ${{ secrets.TEST_DB_USERNAME }} --password=${{ secrets.TEST_DB_PASSWORD }} --silent; then
          echo "MySQL is up and running!"
          break
          else
          echo "Waiting for MySQL to be ready..."
          sleep 5
          fi
          done

      - name: Run Test
        run: SPRING_PROFILES_ACTIVE=local-mysql ./gradlew clean test
        working-directory: ./backend/pokerogue
