name: Backend Production Server CD A

on:
  workflow_call:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [ cd, app-a ]
    steps:
      - name: Change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/2024-pokerogue-helper

      - name: Deploy
        run: |
          cd /home/ubuntu
          
          sudo chmod 666 /var/run/docker.sock
          
          if [ "$(docker ps -qa -f name=server)" ]; then
          docker rm -f server
          else
          echo "No container named 'server' to remove."
          fi
          
          docker pull ${{ secrets.DOCKER_SERVER_IMAGE }}
          
          docker run -d -p 80:8080 --name server \
              -e JAVA_OPTS="-XX:InitialRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0" \
              -e TZ=Asia/Seoul \
              ${{ secrets.DOCKER_SERVER_IMAGE }}

      - name: Wait for service to start
        run: |
          echo "Waiting for the service to start..."
          sleep 10

      - name: Check service availability
        run: |
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8080/actuator/health)
          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "Service is up and running"
          else
            echo "Service is not responding. HTTP Status: $HTTP_STATUS"
            exit 1
          fi
