name: Backend CI

on:
  pull_request:
    branches: [ "be/develop" ]
  push:
    branches: [ "be/develop" ]

permissions:
  contents: read

jobs:
  build:
    env:
      working-directory: ./backend/pokerogue
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Test
        run: ./gradlew clean test
        working-directory: ${{ env.working-directory }}

      - name: Build with Gradle
        run: ./gradlew bootJar
        working-directory: ${{ env.working-directory }}
