name: Backend CI

on:
  push:
    branches: [ "be/infra/#200-update-ci-cd-workflows" ]

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/Backend-Test.yml
    secrets: inherit
