name: Backend Production Server CD

permissions:
  contents: read

on:
  push:
    branches: [ "be/refactor/#502" ]
    tags:
      - 'api-v*'

jobs:
  test:
    uses: ./.github/workflows/Backend-CI.yml
    secrets: inherit

  build:
    needs: test
    runs-on: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew bootJar
        working-directory: ./backend/pokerogue

      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

          docker build -t ${{ secrets.DOCKER_SERVER_IMAGE }} -f ./backend/pokerogue/docker/Dockerfile ./backend/pokerogue
          docker push ${{ secrets.DOCKER_SERVER_IMAGE }}

  deploy:
    needs: build
    runs-on: my-prod-b
    steps:

      - name: Change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/2024-pokerogue-helper

      - name: Deploy
        run: |
          cd /home/ubuntu
          
          sudo chmod 666 /var/run/docker.sock
          
          if [ "$(docker ps -qa -f name=server)" ]; then
          docker rm -f server
          else
          echo "No container named 'server' to remove."
          fi
          
          docker pull ${{ secrets.DOCKER_SERVER_IMAGE }}
          
          docker run -d -p 80:8080 --name server \
              -e JAVA_OPTS="-XX:InitialRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0" \
              -e TZ=Asia/Seoul \
              ${{ secrets.DOCKER_SERVER_IMAGE }}
